/* This file was automagically generated by autoconf */

#define NOsetrgid
#define MAX_argc 7588
/* Your system's strstr() is 1.07 times SLOWER than my C-routine */
#define SLOWstrstr			      /* using my substitute instead */
#define UDP_protocolno 17
#define BIFF_serviceport "512"
#define IP_localhost {127,0,0,1,}
#define TOGGLE_SGID_OK
#define MAILSPOOLDIR "/var/spool/mail/"
#define SENDMAIL "/usr/sbin/sendmail"
#define defPATH "PATH=$HOME/bin:/bin:/usr/bin:/usr/local/bin:/usr/bin/X11"
/*locktype: 4, countlocks: 80, timeout 0, watchdog 14, /tmp/_locktest*/
/*locktype: 2, countlocks: 80, timeout 0, watchdog 14, /tmp/_locktest*/
/*locktype: 1, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 1, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/* Hotwire LOCKINGTEST=001 */
/* Procmail will lock via: dotlocking, flock() */
#define NOfcntl_lock
#define USEflock
/* autoconf completed */
